### PR TITLE
modify_stat_page

### PR DESCRIPTION
**Pull request by ooeyoshinori**
Please confirm it works or not.

### CODE REVIEW

**Comment by hiroaki-iwase** [comment]
Thanks for your pull request.

For prohibiting input irregular value(like a too large, or float),
can you add the validation in rails side, too?(like below.)
https://github.com/roma/gladiator/blob/master/app/models/roma.rb#L40-L46

I propose below value range.
limit of log_shift_age => 1 ~ 1000
(log_shift_size => 1024? ~ ???)

And I think it is better to restrict to integer(not float).

Regards.

**Comment by hiroaki-iwase** [comment]
And please add javascript side validation, too.

Please refer to below file and adding.
"app/assets/javascripts/validate.js"

Thanks.

**Comment by hiroaki-iwase** [comment]
And can you add the rspec test to below area?
https://github.com/roma/gladiator/blob/master/spec/models/roma_spec.rb#L56-L183

Basic format has already developed, so I guess it is ok that only add the new params.

**Comment by ooeyoshinori** [comment]
Would you review again, Mr.Iwase?

**Comment by hiroaki-iwase** [comment]
I reviewed and it looks no problem.
And I made v1.2.0-dev branch.
So I merged into this branch just know.

Thanks for your contribution!!

**Pull request closed without merging**
