### PR TITLE
adjust new Log gathering logic

### PR DESCRIPTION
**Pull request by hiroaki-iwase**

### CODE REVIEW

**Comment by Matsue** [comment]
"Update log" button makes 500 internal server error, could you check it?

**Comment by hiroaki-iwase** [comment]
Thanks for your review.
I planed to abolish update button in this version.
But it still remain resulted from typo.
So I modified it.
Please check again.

**Comment by Matsue** [comment]
Thanks!
In my opinion, it will be better to write following values in constants.rb or create new methods in helper class because those values are used many times.
- Version numbers
  - 2062
  - 65536
  - 65792
- Regexp for strings of time
  - /^(\d+)-(\d+)-(\d+)T(\d+):(\d+):(\d+)$/

As mentioned in https://github.com/roma/roma/pull/40, iso8601 method also will works in this case.

``` Ruby
require 'time'

iso8601_time = '2008-08-31T12:34:56+09:00'
t = Time.iso8601(iso8601_time)
p t       #=> 2008-08-31 03:34:56 UTC
p t.class #=> Time
```

**Comment by Matsue** [comment]
Thanks! :beers:

**Pull request merged**
